healthy_blue:
  outputs:
    dev:
      type: sqlite
      database: 'database'
      schema: main 
      schemas_and_paths:
        main: '../data/health.db'
      schema_directory: '../data'
      threads: 1

  target: dev
