[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[server]
enableStaticServing = true

[theme]
primaryColor = "#DBC04D"
backgroundColor = "#5C594E"
secondaryBackgroundColor = "#282833"
textColor = "#EBEBEB"

[runner]
fastReruns = true
